github_checks:
  annotations: false

ignore:
  - "images/.*"
  - "examples/.*"
  - "cmd/.*"

coverage:
  status:
    project:
      default:
        # pass if coverage drops by no more than 0.05%
        # this is possibly caused by unstable coverage.
        threshold: 0.05%
