header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: CloudWeGo Authors

  paths:
    - '**/*.go'
    - '**/*.s'

  paths-ignore:
    - pkg/common/testdata/**
    - tool/protobuf/api/**

  comment: on-failure
