header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: CloudWeGo Authors

  paths:
    - '**/*.go'
    - '**/*.s'

  paths-ignore:
    - pkg/common/testdata/**
    - cmd/hz/protobuf/api

  comment: on-failure
