name: Cmd Tests

on:
  push:
    paths:
      - 'cmd/**'
  pull_request:
    paths:
      - 'cmd/**'

jobs:
  hz-test-unix:
    runs-on: [ self-hosted, Linux, X64 ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false # don't use cache for self-hosted runners

      - name: Setup Environment
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Hz Test
        run: |
          cd cmd/hz
          sh test_hz_unix.sh


  hz-test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install Protobuf
        shell: pwsh
        run: |
          Invoke-WebRequest https://github.com/protocolbuffers/protobuf/releases/download/v3.19.4/protoc-3.19.4-win64.zip -OutFile protoc-3.19.4-win64.zip
          Expand-Archive protoc-3.19.4-win64.zip -DestinationPath protoc-3.19.4-win64
          $GOPATH=go env GOPATH
          Copy-Item -Path protoc-3.19.4-win64\bin\protoc.exe -Destination $GOPATH\bin
          Copy-Item -Path protoc-3.19.4-win64\include\* -Destination cmd\hz\testdata\include\google -Recurse
          protoc --version

      - name: Hz Test
        run: |
          cd cmd/hz
          sh test_hz_windows.sh
