name: "Labeler"
on:
  issues:
    types: [ opened, edited, reopened ]

jobs:
  triage:
    runs-on: ubuntu-latest
    name: Label issues
    steps:
      - name: check out
        uses: actions/checkout@v3

      - name: labeler
        uses: jbinda/super-labeler-action@develop
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
